// <auto-generated />
namespace Badminton_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class club_personeelMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(club_personeelMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202205051837379_club_personeelMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
