// <auto-generated />
namespace Badminton_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedplayers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedplayers));
        
        string IMigrationMetadata.Id
        {
            get { return "202205261314082_added players"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
