// <auto-generated />
namespace Badminton_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intial_30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial_30));
        
        string IMigrationMetadata.Id
        {
            get { return "202205201242412_intial_3.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
