// <auto-generated />
namespace Badminton_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intial_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202205201307249_intial_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
